/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthcentermanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Cabes-PC
 */
public class Forgotpass extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Forgotpass() {
        initComponents();
    }
    Connection con;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtusername = new javax.swing.JTextField();
        jbtnupdate = new javax.swing.JButton();
        jbtnback = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtxtans = new javax.swing.JTextField();
        jcmbqstn = new javax.swing.JComboBox<>();
        jtxtnpass = new javax.swing.JPasswordField();
        jcheckboxacc = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Forgot password");
        jLabel1.setFocusable(false);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 480, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Username :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("New Password :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jtxtusername.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jPanel3.add(jtxtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 300, 40));

        jbtnupdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnupdate.setText("Reset");
        jbtnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnupdateActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 90, 40));

        jbtnback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnback.setText("Back");
        jbtnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbackActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 90, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Secuirty Question :");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Answer :");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jtxtans.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(jtxtans, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 300, 40));

        jcmbqstn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcmbqstn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your mother’s maiden name?", "What Is your favorite book?", "What was the name of your first pet?", "Where did you go to high school/college?", "What is your favorite food?", "What city were you born in?", "Where is your favorite place to vacation?" }));
        jPanel3.add(jcmbqstn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 300, 50));

        jtxtnpass.setEchoChar('\u25cf');
        jPanel3.add(jtxtnpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 300, 40));

        jcheckboxacc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcheckboxacc.setText("Show Password");
        jcheckboxacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckboxaccActionPerformed(evt);
            }
        });
        jPanel3.add(jcheckboxacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbackActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        this.hide();
        login.setVisible(true);

    }//GEN-LAST:event_jbtnbackActionPerformed

    private void jbtnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnupdateActionPerformed
        // TODO add your handling code here:
        // Update query
        String username = jtxtusername.getText();
        String qstn = jcmbqstn.getSelectedItem().toString();
        String ans = jtxtans.getText();
        String npass = jtxtnpass.getText();

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/healthcenter", "root", "");
            pst = con.prepareStatement("select * from admin where username=? and securityqstn=? AND answer=?");

            pst.setString(1, username);
            pst.setString(2, qstn);
            pst.setString(3, ans);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {

                pst = con.prepareStatement("UPDATE admin SET password=?");
                pst.setString(1, npass);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Password Reset");
                jtxtusername.setText(null);
                jcmbqstn.setSelectedItem("----");
                jtxtans.setText(null);
                jtxtnpass.setText(null);
            } else if (username != ("username")) {
                JOptionPane.showMessageDialog(null, "User doesn't exist");
                jtxtusername.setText(null);
                jcmbqstn.setSelectedItem("----");
                jtxtans.setText(null);
                jtxtnpass.setText(null);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbtnupdateActionPerformed

    private void jcheckboxaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckboxaccActionPerformed
        // TODO add your handling code here:
        if(jcheckboxacc.isSelected()){
           jtxtnpass.setEchoChar((char)0);
            
        }else{
            jtxtnpass.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_jcheckboxaccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgotpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgotpass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtnback;
    private javax.swing.JButton jbtnupdate;
    private javax.swing.JCheckBox jcheckboxacc;
    private javax.swing.JComboBox<String> jcmbqstn;
    private javax.swing.JTextField jtxtans;
    private javax.swing.JPasswordField jtxtnpass;
    private javax.swing.JTextField jtxtusername;
    // End of variables declaration//GEN-END:variables
}
